MOCK_MAILCHIMP_REPOS = """
[{
    "id": 575633,
    "node_id": "MDEwOlJlcG9zaXRvcnk1NzU2MzM=",
    "name": "ChimpKit2",
    "full_name": "mailchimp/ChimpKit2",
    "private": false,
    "owner": {
      "login": "mailchimp",
      "id": 216758,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjIxNjc1OA==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/216758?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mailchimp",
      "html_url": "https://github.com/mailchimp",
      "followers_url": "https://api.github.com/users/mailchimp/followers",
      "following_url": "https://api.github.com/users/mailchimp/following{/other_user}",
      "gists_url": "https://api.github.com/users/mailchimp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mailchimp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mailchimp/subscriptions",
      "organizations_url": "https://api.github.com/users/mailchimp/orgs",
      "repos_url": "https://api.github.com/users/mailchimp/repos",
      "events_url": "https://api.github.com/users/mailchimp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mailchimp/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/mailchimp/ChimpKit2",
    "description": "ChimpKit is Deprecated. Please see ChimpKit 2",
    "fork": false,
    "url": "https://api.github.com/repos/mailchimp/ChimpKit2",
    "forks_url": "https://api.github.com/repos/mailchimp/ChimpKit2/forks",
    "keys_url": "https://api.github.com/repos/mailchimp/ChimpKit2/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/mailchimp/ChimpKit2/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/mailchimp/ChimpKit2/teams",
    "hooks_url": "https://api.github.com/repos/mailchimp/ChimpKit2/hooks",
    "issue_events_url": "https://api.github.com/repos/mailchimp/ChimpKit2/issues/events{/number}",
    "events_url": "https://api.github.com/repos/mailchimp/ChimpKit2/events",
    "assignees_url": "https://api.github.com/repos/mailchimp/ChimpKit2/assignees{/user}",
    "branches_url": "https://api.github.com/repos/mailchimp/ChimpKit2/branches{/branch}",
    "tags_url": "https://api.github.com/repos/mailchimp/ChimpKit2/tags",
    "blobs_url": "https://api.github.com/repos/mailchimp/ChimpKit2/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/mailchimp/ChimpKit2/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/mailchimp/ChimpKit2/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/mailchimp/ChimpKit2/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/mailchimp/ChimpKit2/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/mailchimp/ChimpKit2/languages",
    "stargazers_url": "https://api.github.com/repos/mailchimp/ChimpKit2/stargazers",
    "contributors_url": "https://api.github.com/repos/mailchimp/ChimpKit2/contributors",
    "subscribers_url": "https://api.github.com/repos/mailchimp/ChimpKit2/subscribers",
    "subscription_url": "https://api.github.com/repos/mailchimp/ChimpKit2/subscription",
    "commits_url": "https://api.github.com/repos/mailchimp/ChimpKit2/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/mailchimp/ChimpKit2/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/mailchimp/ChimpKit2/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/mailchimp/ChimpKit2/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/mailchimp/ChimpKit2/contents/{+path}",
    "compare_url": "https://api.github.com/repos/mailchimp/ChimpKit2/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/mailchimp/ChimpKit2/merges",
    "archive_url": "https://api.github.com/repos/mailchimp/ChimpKit2/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/mailchimp/ChimpKit2/downloads",
    "issues_url": "https://api.github.com/repos/mailchimp/ChimpKit2/issues{/number}",
    "pulls_url": "https://api.github.com/repos/mailchimp/ChimpKit2/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/mailchimp/ChimpKit2/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/mailchimp/ChimpKit2/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/mailchimp/ChimpKit2/labels{/name}",
    "releases_url": "https://api.github.com/repos/mailchimp/ChimpKit2/releases{/id}",
    "deployments_url": "https://api.github.com/repos/mailchimp/ChimpKit2/deployments",
    "created_at": "2010-03-23T13:15:43Z",
    "updated_at": "2018-09-24T15:22:02Z",
    "pushed_at": "2011-04-07T02:16:40Z",
    "git_url": "git://github.com/mailchimp/ChimpKit2.git",
    "ssh_url": "git@github.com:mailchimp/ChimpKit2.git",
    "clone_url": "https://github.com/mailchimp/ChimpKit2.git",
    "svn_url": "https://github.com/mailchimp/ChimpKit2",
    "homepage": "http://github.com/mailchimp/chimpkit2",
    "size": 736,
    "stargazers_count": 29,
    "watchers_count": 29,
    "language": "Objective-C",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 1,
    "mirror_url": null,
    "archived": true,
    "disabled": false,
    "open_issues_count": 3,
    "license": null,
    "forks": 1,
    "open_issues": 3,
    "watchers": 29,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "push": false,
      "pull": true
    }
  },
  {
    "id": 981065,
    "node_id": "MDEwOlJlcG9zaXRvcnk5ODEwNjU=",
    "name": "email-blueprints",
    "full_name": "mailchimp/email-blueprints",
    "private": false,
    "owner": {
      "login": "mailchimp",
      "id": 216758,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjIxNjc1OA==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/216758?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mailchimp",
      "html_url": "https://github.com/mailchimp",
      "followers_url": "https://api.github.com/users/mailchimp/followers",
      "following_url": "https://api.github.com/users/mailchimp/following{/other_user}",
      "gists_url": "https://api.github.com/users/mailchimp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mailchimp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mailchimp/subscriptions",
      "organizations_url": "https://api.github.com/users/mailchimp/orgs",
      "repos_url": "https://api.github.com/users/mailchimp/repos",
      "events_url": "https://api.github.com/users/mailchimp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mailchimp/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/mailchimp/email-blueprints",
    "description": "Email Blueprints is a collection of HTML email templates that can serve as a solid foundation and starting point for the design of emails",
    "fork": false,
    "url": "https://api.github.com/repos/mailchimp/email-blueprints",
    "forks_url": "https://api.github.com/repos/mailchimp/email-blueprints/forks",
    "keys_url": "https://api.github.com/repos/mailchimp/email-blueprints/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/mailchimp/email-blueprints/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/mailchimp/email-blueprints/teams",
    "hooks_url": "https://api.github.com/repos/mailchimp/email-blueprints/hooks",
    "issue_events_url": "https://api.github.com/repos/mailchimp/email-blueprints/issues/events{/number}",
    "events_url": "https://api.github.com/repos/mailchimp/email-blueprints/events",
    "assignees_url": "https://api.github.com/repos/mailchimp/email-blueprints/assignees{/user}",
    "branches_url": "https://api.github.com/repos/mailchimp/email-blueprints/branches{/branch}",
    "tags_url": "https://api.github.com/repos/mailchimp/email-blueprints/tags",
    "blobs_url": "https://api.github.com/repos/mailchimp/email-blueprints/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/mailchimp/email-blueprints/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/mailchimp/email-blueprints/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/mailchimp/email-blueprints/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/mailchimp/email-blueprints/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/mailchimp/email-blueprints/languages",
    "stargazers_url": "https://api.github.com/repos/mailchimp/email-blueprints/stargazers",
    "contributors_url": "https://api.github.com/repos/mailchimp/email-blueprints/contributors",
    "subscribers_url": "https://api.github.com/repos/mailchimp/email-blueprints/subscribers",
    "subscription_url": "https://api.github.com/repos/mailchimp/email-blueprints/subscription",
    "commits_url": "https://api.github.com/repos/mailchimp/email-blueprints/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/mailchimp/email-blueprints/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/mailchimp/email-blueprints/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/mailchimp/email-blueprints/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/mailchimp/email-blueprints/contents/{+path}",
    "compare_url": "https://api.github.com/repos/mailchimp/email-blueprints/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/mailchimp/email-blueprints/merges",
    "archive_url": "https://api.github.com/repos/mailchimp/email-blueprints/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/mailchimp/email-blueprints/downloads",
    "issues_url": "https://api.github.com/repos/mailchimp/email-blueprints/issues{/number}",
    "pulls_url": "https://api.github.com/repos/mailchimp/email-blueprints/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/mailchimp/email-blueprints/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/mailchimp/email-blueprints/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/mailchimp/email-blueprints/labels{/name}",
    "releases_url": "https://api.github.com/repos/mailchimp/email-blueprints/releases{/id}",
    "deployments_url": "https://api.github.com/repos/mailchimp/email-blueprints/deployments",
    "created_at": "2010-10-12T12:28:30Z",
    "updated_at": "2020-10-30T11:38:05Z",
    "pushed_at": "2019-10-23T04:38:04Z",
    "git_url": "git://github.com/mailchimp/email-blueprints.git",
    "ssh_url": "git@github.com:mailchimp/email-blueprints.git",
    "clone_url": "https://github.com/mailchimp/email-blueprints.git",
    "svn_url": "https://github.com/mailchimp/email-blueprints",
    "homepage": "http://templates.mailchimp.com",
    "size": 2914,
    "stargazers_count": 6753,
    "watchers_count": 6753,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 2806,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 36,
    "license": null,
    "forks": 2806,
    "open_issues": 36,
    "watchers": 6753,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "push": false,
      "pull": true
    }
  },
  {
    "id": 1382747,
    "node_id": "MDEwOlJlcG9zaXRvcnkxMzgyNzQ3",
    "name": "MailChimp.tmbundle",
    "full_name": "mailchimp/MailChimp.tmbundle",
    "private": false,
    "owner": {
      "login": "mailchimp",
      "id": 216758,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjIxNjc1OA==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/216758?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mailchimp",
      "html_url": "https://github.com/mailchimp",
      "followers_url": "https://api.github.com/users/mailchimp/followers",
      "following_url": "https://api.github.com/users/mailchimp/following{/other_user}",
      "gists_url": "https://api.github.com/users/mailchimp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mailchimp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mailchimp/subscriptions",
      "organizations_url": "https://api.github.com/users/mailchimp/orgs",
      "repos_url": "https://api.github.com/users/mailchimp/repos",
      "events_url": "https://api.github.com/users/mailchimp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mailchimp/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/mailchimp/MailChimp.tmbundle",
    "description": "MailChimp TextMate Bundle",
    "fork": false,
    "url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle",
    "forks_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/forks",
    "keys_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/teams",
    "hooks_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/hooks",
    "issue_events_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/issues/events{/number}",
    "events_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/events",
    "assignees_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/assignees{/user}",
    "branches_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/branches{/branch}",
    "tags_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/tags",
    "blobs_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/languages",
    "stargazers_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/stargazers",
    "contributors_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/contributors",
    "subscribers_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/subscribers",
    "subscription_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/subscription",
    "commits_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/contents/{+path}",
    "compare_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/merges",
    "archive_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/downloads",
    "issues_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/issues{/number}",
    "pulls_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/labels{/name}",
    "releases_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/releases{/id}",
    "deployments_url": "https://api.github.com/repos/mailchimp/MailChimp.tmbundle/deployments",
    "created_at": "2011-02-18T14:35:53Z",
    "updated_at": "2018-12-14T19:31:28Z",
    "pushed_at": "2013-02-19T19:30:45Z",
    "git_url": "git://github.com/mailchimp/MailChimp.tmbundle.git",
    "ssh_url": "git@github.com:mailchimp/MailChimp.tmbundle.git",
    "clone_url": "https://github.com/mailchimp/MailChimp.tmbundle.git",
    "svn_url": "https://github.com/mailchimp/MailChimp.tmbundle",
    "homepage": "",
    "size": 241,
    "stargazers_count": 24,
    "watchers_count": 24,
    "language": "PHP",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 10,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1,
    "license": null,
    "forks": 10,
    "open_issues": 1,
    "watchers": 24,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "push": false,
      "pull": true
    }
  }]
  """

SAMPLE_TOPICS = """
{
  "names": [
      "topic 1",
      "topic 2"
  ]
}
"""


SAMPLE_AGGRAGATED_REPOS = [
    {
        "language": "Objective-C",
        "private": False,
        "fork": False,
        "watchers": 10,
        "topics": ["topic 1", "topic 2"],
    },
    {
        "language": "Python",
        "private": False,
        "fork": True,
        "watchers": 20,
        "topics": ["topic 1"],
    },
    {
        "language": "Objective-C",
        "private": True,
        "fork": False,
        "watchers": 100,
        "topics": ["secrete topic"],
    },
    {
        "language": "Javascript",
        "private": False,
        "fork": False,
        "watchers": 3,
        "topics": ["topic 1", "topic 3"],
    },
    {
        "language": "Python",
        "private": False,
        "fork": False,
        "watchers": 1,
        "topics": ["topic 4"],
    },
    {"private": False, "fork": True, "watchers": 1, "topics": []},
]
